// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcScxrEWXnRT6WRWDljS4Fo8w2NcE6phU',
    appId: '1:559131762601:web:b5a4e18357d0a329fa6eb8',
    messagingSenderId: '559131762601',
    projectId: 'proyectovcm-3f3d1',
    authDomain: 'proyectovcm-3f3d1.firebaseapp.com',
    storageBucket: 'proyectovcm-3f3d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi27n043iMuEgkvBGUuajum25xId4KXuM',
    appId: '1:559131762601:android:e9b80e37249b46c0fa6eb8',
    messagingSenderId: '559131762601',
    projectId: 'proyectovcm-3f3d1',
    storageBucket: 'proyectovcm-3f3d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXgQMpaJVwmNGLXyldmCrXj0eWczq4CY',
    appId: '1:559131762601:ios:b59f475868048ea8fa6eb8',
    messagingSenderId: '559131762601',
    projectId: 'proyectovcm-3f3d1',
    storageBucket: 'proyectovcm-3f3d1.firebasestorage.app',
    iosBundleId: 'cl.baza.proyectovcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxXgQMpaJVwmNGLXyldmCrXj0eWczq4CY',
    appId: '1:559131762601:ios:b59f475868048ea8fa6eb8',
    messagingSenderId: '559131762601',
    projectId: 'proyectovcm-3f3d1',
    storageBucket: 'proyectovcm-3f3d1.firebasestorage.app',
    iosBundleId: 'cl.baza.proyectovcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcScxrEWXnRT6WRWDljS4Fo8w2NcE6phU',
    appId: '1:559131762601:web:09860ed22d8ca6abfa6eb8',
    messagingSenderId: '559131762601',
    projectId: 'proyectovcm-3f3d1',
    authDomain: 'proyectovcm-3f3d1.firebaseapp.com',
    storageBucket: 'proyectovcm-3f3d1.firebasestorage.app',
  );
}
